// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.starrocks.catalog;

import org.xerial.snappy.Snappy;

import java.io.Closeable;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Pure Java LevelDB SSTable reader, inverse of KVIndexSSTWriter.
 * Reads SSTable files generated by KVIndexSSTWriter and decodes all KV entries.
 */
public class KVIndexSSTReader implements Closeable {

    private static final long TABLE_MAGIC_NUMBER = 0xdb4775248b80fb57L;
    private static final int FOOTER_ENCODED_LENGTH = 48;
    private static final int BLOCK_TRAILER_SIZE = 5;
    private static final byte COMPRESSION_NONE = 0;
    private static final byte COMPRESSION_SNAPPY = 1;

    private final RandomAccessFile file;
    private final long fileLength;

    // Parsed from footer
    private long indexBlockOffset;
    private long indexBlockSize;

    private KVIndexSSTReader(RandomAccessFile file, long fileLength) {
        this.file = file;
        this.fileLength = fileLength;
    }

    public static KVIndexSSTReader open(String filePath) throws IOException {
        RandomAccessFile raf = new RandomAccessFile(filePath, "r");
        long fileLength = raf.length();
        if (fileLength < FOOTER_ENCODED_LENGTH) {
            raf.close();
            throw new IOException("File too small to be a valid SSTable: " + fileLength);
        }

        KVIndexSSTReader reader = new KVIndexSSTReader(raf, fileLength);
        reader.readFooter();
        return reader;
    }

    private void readFooter() throws IOException {
        byte[] footer = new byte[FOOTER_ENCODED_LENGTH];
        file.seek(fileLength - FOOTER_ENCODED_LENGTH);
        file.readFully(footer);

        // Verify magic number (last 8 bytes, little-endian)
        int magicLo = getFixed32(footer, 40);
        int magicHi = getFixed32(footer, 44);
        long magic = (Integer.toUnsignedLong(magicLo)) | (Integer.toUnsignedLong(magicHi) << 32);
        if (magic != TABLE_MAGIC_NUMBER) {
            throw new IOException(String.format("Invalid SSTable magic: 0x%016X (expected 0x%016X)",
                    magic, TABLE_MAGIC_NUMBER));
        }

        // Parse metaindex handle (we skip it, just need to advance past it)
        int[] pos = {0};
        getVarint64(footer, pos); // metaindex offset
        getVarint64(footer, pos); // metaindex size

        // Parse index handle
        indexBlockOffset = getVarint64(footer, pos);
        indexBlockSize = getVarint64(footer, pos);
    }

    /**
     * Read all entries from the SSTable.
     *
     * @param columnNames array of column names for the value columns
     * @param columnTypes array of column type names (INT, BIGINT, DOUBLE, VARCHAR, etc.)
     * @return list of decoded KV entries
     */
    public List<KVEntry> readAll(String[] columnNames, String[] columnTypes) throws IOException {
        // 1. Read index block to get data block handles
        byte[] indexBlockRaw = readBlock(indexBlockOffset, indexBlockSize);
        List<BlockHandle> dataBlockHandles = parseIndexBlock(indexBlockRaw);

        // 2. Read each data block and decode entries
        List<KVEntry> entries = new ArrayList<>();
        for (BlockHandle handle : dataBlockHandles) {
            byte[] dataBlockRaw = readBlock(handle.offset, handle.size);
            decodeDataBlock(dataBlockRaw, columnNames, columnTypes, entries);
        }

        return entries;
    }

    private byte[] readBlock(long offset, long size) throws IOException {
        // Read block contents + trailer
        int totalSize = (int) size + BLOCK_TRAILER_SIZE;
        byte[] raw = new byte[totalSize];
        file.seek(offset);
        file.readFully(raw);

        byte compressionType = raw[(int) size];
        // Skip CRC verification for v1

        byte[] blockData = new byte[(int) size];
        System.arraycopy(raw, 0, blockData, 0, (int) size);

        if (compressionType == COMPRESSION_SNAPPY) {
            return Snappy.uncompress(blockData);
        } else if (compressionType == COMPRESSION_NONE) {
            return blockData;
        } else {
            throw new IOException("Unknown compression type: " + compressionType);
        }
    }

    private List<BlockHandle> parseIndexBlock(byte[] block) throws IOException {
        List<BlockHandle> handles = new ArrayList<>();
        // Index block has restart array at the end
        int numRestarts = getFixed32(block, block.length - 4);
        int restartArrayStart = block.length - 4 - numRestarts * 4;

        // Parse prefix-compressed entries
        int[] pos = {0};
        byte[] lastKey = new byte[0];
        while (pos[0] < restartArrayStart) {
            int sharedBytes = getVarint32(block, pos);
            int unsharedBytes = getVarint32(block, pos);
            int valueLength = getVarint32(block, pos);

            // Reconstruct full key
            byte[] key = new byte[sharedBytes + unsharedBytes];
            System.arraycopy(lastKey, 0, key, 0, sharedBytes);
            System.arraycopy(block, pos[0], key, sharedBytes, unsharedBytes);
            pos[0] += unsharedBytes;

            // Parse value as BlockHandle
            int[] handlePos = {pos[0]};
            long handleOffset = getVarint64(block, handlePos);
            long handleSize = getVarint64(block, handlePos);
            handles.add(new BlockHandle(handleOffset, handleSize));
            pos[0] += valueLength;

            lastKey = key;
        }

        return handles;
    }

    private void decodeDataBlock(byte[] block, String[] columnNames, String[] columnTypes,
                                 List<KVEntry> entries) throws IOException {
        int numRestarts = getFixed32(block, block.length - 4);
        int restartArrayStart = block.length - 4 - numRestarts * 4;

        int[] pos = {0};
        byte[] lastKey = new byte[0];
        while (pos[0] < restartArrayStart) {
            int sharedBytes = getVarint32(block, pos);
            int unsharedBytes = getVarint32(block, pos);
            int valueLength = getVarint32(block, pos);

            // Reconstruct full key
            byte[] key = new byte[sharedBytes + unsharedBytes];
            System.arraycopy(lastKey, 0, key, 0, sharedBytes);
            System.arraycopy(block, pos[0], key, sharedBytes, unsharedBytes);
            pos[0] += unsharedBytes;

            // Extract value
            byte[] value = new byte[valueLength];
            System.arraycopy(block, pos[0], value, 0, valueLength);
            pos[0] += valueLength;

            // Decode key → rowId
            long rowId = decodeInt64Key(key);

            // Decode value → column values
            Object[] values = decodeRowValue(value, columnTypes);

            entries.add(new KVEntry(rowId, columnNames, values));
            lastKey = key;
        }
    }

    /**
     * Decode int64 key (inverse of KVIndexSSTWriter.encodeInt64Key).
     * big-endian → XOR MIN_VALUE → signed int64
     */
    static long decodeInt64Key(byte[] key) {
        if (key.length != 8) {
            throw new IllegalArgumentException("Expected 8-byte key, got " + key.length);
        }
        long unsigned = 0;
        for (int i = 0; i < 8; i++) {
            unsigned = (unsigned << 8) | (key[i] & 0xFF);
        }
        return unsigned ^ Long.MIN_VALUE;
    }

    /**
     * Decode row value (inverse of KVIndexSSTWriter.encodeRowValue).
     * Format: per-column [1B null_flag][raw_data if not null]
     * Matching NullableColumn::serialize / deserialize_and_append in BE.
     */
    static Object[] decodeRowValue(byte[] value, String[] columnTypes) {
        int numCols = columnTypes.length;
        int[] pos = {0};
        Object[] result = new Object[numCols];

        for (int i = 0; i < numCols; i++) {
            int nullFlag = value[pos[0]] & 0xFF;
            pos[0]++;
            if (nullFlag != 0) {
                result[i] = null;
            } else {
                result[i] = deserializeColumn(value, pos, columnTypes[i]);
            }
        }

        return result;
    }

    private static Object deserializeColumn(byte[] data, int[] pos, String type) {
        ByteBuffer bb;
        switch (type.toUpperCase()) {
            case "INT":
            case "INT32":
            case "INTEGER":
                bb = ByteBuffer.wrap(data, pos[0], 4).order(ByteOrder.LITTLE_ENDIAN);
                pos[0] += 4;
                return bb.getInt();
            case "BIGINT":
            case "INT64":
            case "LONG":
                bb = ByteBuffer.wrap(data, pos[0], 8).order(ByteOrder.LITTLE_ENDIAN);
                pos[0] += 8;
                return bb.getLong();
            case "FLOAT":
                bb = ByteBuffer.wrap(data, pos[0], 4).order(ByteOrder.LITTLE_ENDIAN);
                pos[0] += 4;
                return bb.getFloat();
            case "DOUBLE":
                bb = ByteBuffer.wrap(data, pos[0], 8).order(ByteOrder.LITTLE_ENDIAN);
                pos[0] += 8;
                return bb.getDouble();
            case "VARCHAR":
            case "STRING":
            case "CHAR": {
                bb = ByteBuffer.wrap(data, pos[0], 4).order(ByteOrder.LITTLE_ENDIAN);
                int strLen = bb.getInt();
                pos[0] += 4;
                String str = new String(data, pos[0], strLen, StandardCharsets.UTF_8);
                pos[0] += strLen;
                return str;
            }
            default: {
                // Fallback: treat as VARCHAR
                bb = ByteBuffer.wrap(data, pos[0], 4).order(ByteOrder.LITTLE_ENDIAN);
                int strLen = bb.getInt();
                pos[0] += 4;
                String str = new String(data, pos[0], strLen, StandardCharsets.UTF_8);
                pos[0] += strLen;
                return str;
            }
        }
    }

    private static long getVarint64(byte[] data, int[] pos) {
        long result = 0;
        int shift = 0;
        while (pos[0] < data.length) {
            byte b = data[pos[0]++];
            result |= (long) (b & 0x7F) << shift;
            if ((b & 0x80) == 0) {
                return result;
            }
            shift += 7;
        }
        throw new IllegalArgumentException("Truncated varint64");
    }

    private static int getVarint32(byte[] data, int[] pos) {
        return (int) getVarint64(data, pos);
    }

    @Override
    public void close() throws IOException {
        file.close();
    }

    // --- Data classes ---

    public static class KVEntry {
        public final long rowId;
        public final String[] columnNames;
        public final Object[] values;

        public KVEntry(long rowId, String[] columnNames, Object[] values) {
            this.rowId = rowId;
            this.columnNames = columnNames;
            this.values = values;
        }
    }

    private static class BlockHandle {
        final long offset;
        final long size;

        BlockHandle(long offset, long size) {
            this.offset = offset;
            this.size = size;
        }
    }
}
