# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import coordinator_pb2 as coordinator__pb2


class DaftCoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitDaftPlan = channel.unary_stream(
                '/starrocks.coordinator.DaftCoordinator/SubmitDaftPlan',
                request_serializer=coordinator__pb2.DaftPlanRequest.SerializeToString,
                response_deserializer=coordinator__pb2.DaftPlanResponse.FromString,
                )
        self.RegisterFunction = channel.unary_unary(
                '/starrocks.coordinator.DaftCoordinator/RegisterFunction',
                request_serializer=coordinator__pb2.RegisterFunctionRequest.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterFunctionResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/starrocks.coordinator.DaftCoordinator/GetStatus',
                request_serializer=coordinator__pb2.StatusRequest.SerializeToString,
                response_deserializer=coordinator__pb2.StatusResponse.FromString,
                )
        self.ListFunctions = channel.unary_unary(
                '/starrocks.coordinator.DaftCoordinator/ListFunctions',
                request_serializer=coordinator__pb2.ListFunctionsRequest.SerializeToString,
                response_deserializer=coordinator__pb2.ListFunctionsResponse.FromString,
                )
        self.UnregisterFunction = channel.unary_unary(
                '/starrocks.coordinator.DaftCoordinator/UnregisterFunction',
                request_serializer=coordinator__pb2.UnregisterFunctionRequest.SerializeToString,
                response_deserializer=coordinator__pb2.UnregisterFunctionResponse.FromString,
                )


class DaftCoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitDaftPlan(self, request, context):
        """Submit a Daft execution plan, return Arrow IPC results (server streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFunction(self, request, context):
        """Register a Python function for use in map_batches.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Health check and status query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFunctions(self, request, context):
        """List all registered functions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterFunction(self, request, context):
        """Unregister a previously registered function.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaftCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitDaftPlan': grpc.unary_stream_rpc_method_handler(
                    servicer.SubmitDaftPlan,
                    request_deserializer=coordinator__pb2.DaftPlanRequest.FromString,
                    response_serializer=coordinator__pb2.DaftPlanResponse.SerializeToString,
            ),
            'RegisterFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFunction,
                    request_deserializer=coordinator__pb2.RegisterFunctionRequest.FromString,
                    response_serializer=coordinator__pb2.RegisterFunctionResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=coordinator__pb2.StatusRequest.FromString,
                    response_serializer=coordinator__pb2.StatusResponse.SerializeToString,
            ),
            'ListFunctions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFunctions,
                    request_deserializer=coordinator__pb2.ListFunctionsRequest.FromString,
                    response_serializer=coordinator__pb2.ListFunctionsResponse.SerializeToString,
            ),
            'UnregisterFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterFunction,
                    request_deserializer=coordinator__pb2.UnregisterFunctionRequest.FromString,
                    response_serializer=coordinator__pb2.UnregisterFunctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'starrocks.coordinator.DaftCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DaftCoordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitDaftPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/starrocks.coordinator.DaftCoordinator/SubmitDaftPlan',
            coordinator__pb2.DaftPlanRequest.SerializeToString,
            coordinator__pb2.DaftPlanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starrocks.coordinator.DaftCoordinator/RegisterFunction',
            coordinator__pb2.RegisterFunctionRequest.SerializeToString,
            coordinator__pb2.RegisterFunctionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starrocks.coordinator.DaftCoordinator/GetStatus',
            coordinator__pb2.StatusRequest.SerializeToString,
            coordinator__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFunctions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starrocks.coordinator.DaftCoordinator/ListFunctions',
            coordinator__pb2.ListFunctionsRequest.SerializeToString,
            coordinator__pb2.ListFunctionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnregisterFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starrocks.coordinator.DaftCoordinator/UnregisterFunction',
            coordinator__pb2.UnregisterFunctionRequest.SerializeToString,
            coordinator__pb2.UnregisterFunctionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
