# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from starrocks.coordinator.proto import coordinator_pb2 as coordinator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaftCoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitDaftPlan = channel.unary_stream(
                '/starrocks.coordinator.DaftCoordinator/SubmitDaftPlan',
                request_serializer=coordinator__pb2.DaftPlanRequest.SerializeToString,
                response_deserializer=coordinator__pb2.DaftPlanResponse.FromString,
                _registered_method=True)
        self.RegisterFunction = channel.unary_unary(
                '/starrocks.coordinator.DaftCoordinator/RegisterFunction',
                request_serializer=coordinator__pb2.RegisterFunctionRequest.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterFunctionResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/starrocks.coordinator.DaftCoordinator/GetStatus',
                request_serializer=coordinator__pb2.StatusRequest.SerializeToString,
                response_deserializer=coordinator__pb2.StatusResponse.FromString,
                _registered_method=True)


class DaftCoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitDaftPlan(self, request, context):
        """Submit a Daft execution plan, return Arrow IPC results (server streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFunction(self, request, context):
        """Register a Python function for use in map_batches.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Health check and status query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaftCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitDaftPlan': grpc.unary_stream_rpc_method_handler(
                    servicer.SubmitDaftPlan,
                    request_deserializer=coordinator__pb2.DaftPlanRequest.FromString,
                    response_serializer=coordinator__pb2.DaftPlanResponse.SerializeToString,
            ),
            'RegisterFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFunction,
                    request_deserializer=coordinator__pb2.RegisterFunctionRequest.FromString,
                    response_serializer=coordinator__pb2.RegisterFunctionResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=coordinator__pb2.StatusRequest.FromString,
                    response_serializer=coordinator__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'starrocks.coordinator.DaftCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('starrocks.coordinator.DaftCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaftCoordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitDaftPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/starrocks.coordinator.DaftCoordinator/SubmitDaftPlan',
            coordinator__pb2.DaftPlanRequest.SerializeToString,
            coordinator__pb2.DaftPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/starrocks.coordinator.DaftCoordinator/RegisterFunction',
            coordinator__pb2.RegisterFunctionRequest.SerializeToString,
            coordinator__pb2.RegisterFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/starrocks.coordinator.DaftCoordinator/GetStatus',
            coordinator__pb2.StatusRequest.SerializeToString,
            coordinator__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
